# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-name: '@metamask/*'
      - dependency-name: '@ethereumjs/*'
      - dependency-name: 'libsodium-wrappers'
    target-branch: 'staging'
    versioning-strategy: 'increase'
    open-pull-requests-limit: 5