name: Continuous Integration

on:
  push:
    branches:
    - CI/CD

  pull_request:
    branches:
    - CI/CD


jobs:
  test:
    environment: CI
    name: E2e tests
    runs-on: silent-shard-snap
    strategy:
      matrix:
        node-version: ['18.x']

    steps:
    - uses: actions/checkout@v4
    - run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
    - run: echo "APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
    - run: npm i
    - run: npm test